from __future__ import annotations

LESSONS = [
    {
        "id": "01",
        "title": "Ingest without changing the source",
        "module": "med_io",
        "function": "load_medical_image_bytes",
        "plain": "Read a medical image into memory while keeping the original file conceptually separate from the display version.",
        "why": "If the display image and the evidence source become the same editable object, later annotations or reconstructions can accidentally be mistaken for original evidence.",
        "input": "PNG/JPG/WebP or a single DICOM object",
        "output": "Rendered RGB image plus minimal source metadata",
        "failure": "Unsupported file, empty image, unreadable pixel data, or DICOM without PixelData.",
        "fix": "Reject the file cleanly, report the decoder error, and keep the source untouched. Never invent pixels.",
        "check": "Unit tests confirm standard image and public CT/MR DICOM ingestion.",
    },
    {
        "id": "02",
        "title": "Minimize DICOM metadata",
        "module": "med_io",
        "function": "load_dicom_bytes",
        "plain": "Decode the pixel data we need for viewing without carrying the entire DICOM header into MedForge project exports.",
        "why": "DICOM headers can contain patient identifiers and acquisition metadata. The visualization project should not silently become a copy of the clinical archive.",
        "input": "One DICOM object",
        "output": "Rendered pixels, modality, dimensions, and no raw Dataset object",
        "failure": "A developer accidentally serializes the pydicom Dataset or copies patient fields into the project JSON.",
        "fix": "Use explicit safe summaries and test that identifiers never appear in serialized output.",
        "check": "Synthetic DICOM tests intentionally include fake PatientName/PatientID and verify they do not appear in safe summaries.",
    },
    {
        "id": "03",
        "title": "Group a DICOM study into series",
        "module": "med_volume",
        "function": "inspect_dicom_series",
        "plain": "Separate a folder or ZIP into imaging series before trying to build a 3D volume.",
        "why": "One study may contain scouts, localizers, different sequences, reconstructions, or multiple body regions. Stacking all files together would create nonsense.",
        "input": "Multiple DICOM byte streams",
        "output": "PHI-minimized series list with modality, description, dimensions, and instance counts",
        "failure": "Different series are mixed together or non-image DICOM objects are treated as slices.",
        "fix": "Group by SeriesInstanceUID and only build from pixel-bearing instances in the selected series.",
        "check": "The series tests create multiple DICOM slices and verify instance grouping.",
    },
    {
        "id": "04",
        "title": "Assemble the 3D voxel volume",
        "module": "med_volume",
        "function": "build_dicom_volume",
        "plain": "Sort compatible slices in physical order and stack them into one z-y-x array.",
        "why": "A 3D model only makes sense when slice order, orientation, spacing, rescale slope, and intercept are handled consistently.",
        "input": "One selected DICOM series",
        "output": "Float32 voxel volume plus spacing and decode warnings",
        "failure": "Slices are reversed, instance numbers are unreliable, a compressed codec is missing, or dimensions change mid-series.",
        "fix": "Prefer ImagePositionPatient + ImageOrientationPatient, fall back carefully, surface decoder errors, and reject incompatible shapes.",
        "check": "Synthetic geometry tests verify correct z-order and spacing; public CT/MR DICOM smoke tests exercise the real decoder.",
    },
    {
        "id": "05",
        "title": "Reformat into axial, coronal, and sagittal views",
        "module": "med_volume",
        "function": "mpr_slices",
        "plain": "Cut the same 3D array in three directions so we can inspect the study from different planes.",
        "why": "This lets us follow a structure through the volume instead of interpreting one isolated screenshot.",
        "input": "3D z-y-x volume and three cursor positions",
        "output": "Axial, coronal, and sagittal image planes",
        "failure": "Axes get swapped or flipped and the viewer labels the wrong plane.",
        "fix": "Keep one internal axis convention, test the output shapes, and label display reformats as reformats—not new acquisitions.",
        "check": "MPR unit tests validate each plane's expected shape.",
    },
    {
        "id": "06",
        "title": "Make a lightweight 3D preview",
        "module": "med_volume",
        "function": "downsample_volume",
        "plain": "Reduce a large volume before sending voxels to the browser for a 3D intensity preview.",
        "why": "Sending millions of voxels to a browser can make the viewer unusable. A preview is for orientation, not diagnosis.",
        "input": "Full-resolution 3D volume",
        "output": "Smaller volume retaining the broad spatial pattern",
        "failure": "The app freezes, memory usage spikes, or the preview is mistaken for segmentation.",
        "fix": "Downsample deterministically and label the result as an intensity preview.",
        "check": "The viewer caps each preview axis before plotting.",
    },
    {
        "id": "07",
        "title": "Prove the mask pipeline before adding AI segmentation",
        "module": "med_segmentation",
        "function": "percentile_mask",
        "plain": "Create a simple threshold mask so we can test the entire mask/view/render pipeline without pretending we have identified anatomy.",
        "why": "It is safer to prove the plumbing with a meaningless mask than to wire in a segmentation model and accidentally present its output as clinically authoritative.",
        "input": "3D volume + percentile",
        "output": "Boolean voxel mask",
        "failure": "A threshold mask is labeled as a structure or pathology.",
        "fix": "Call it an exploratory intensity mask and reserve anatomical names for reviewed segmentation outputs.",
        "check": "Tests assert that the summary explicitly says the mask is not anatomical.",
    },
    {
        "id": "08",
        "title": "Separate observations from interpretation",
        "module": "med_engine",
        "function": "build_medical_vlm_prompt",
        "plain": "Force the image-understanding step to report visible observations, uncertainty, and questions separately.",
        "why": "This is one of MedForge's most important rules: a model should not quietly turn a visual impression into a diagnosis or causal mechanism.",
        "input": "Modality, body region, and the user's question",
        "output": "Provider-neutral medical vision prompt with evidence boundaries",
        "failure": "The model invents a measurement, overstates a finding, or folds the user's history into what it says is visible.",
        "fix": "Require visible observations, limitations, and clinical-correlation questions as separate sections.",
        "check": "Tests verify that the prompt includes uncertainty, no-diagnosis, and no-causation instructions.",
    },
    {
        "id": "09",
        "title": "Build a mechanism as a hypothesis",
        "module": "med_engine",
        "function": "build_mechanism_steps",
        "plain": "Turn a proposed motion or loading condition into a storyboard without claiming the storyboard proves what happened.",
        "why": "Mechanism animation can be persuasive. That makes epistemic labeling more important, not less.",
        "input": "Region, structures, mechanism family, proposed motion, and proposed effect",
        "output": "Six-step storyboard from source anatomy through hypothesis and back to evidence",
        "failure": "An illustrative reconstruction is shown as though it were captured by the scan.",
        "fix": "Label every synthesized step and always return to the source image at the end.",
        "check": "Tests verify SOURCE-OBSERVED, HYPOTHESIZED, and EVIDENCE CHECK states remain distinct.",
    },
    {
        "id": "10",
        "title": "Export an auditable render plan",
        "module": "med_engine",
        "function": "build_render_manifest",
        "plain": "Package labels, mechanism steps, and render rules into a portable plan for a later video or 3D renderer.",
        "why": "A renderer should receive the same evidence boundaries as the UI. Otherwise a downstream animation tool could erase the distinction between evidence and reconstruction.",
        "input": "Project title, source identity, labels, and mechanism steps",
        "output": "Provider-neutral render manifest",
        "failure": "A downstream renderer redraws the source, removes uncertainty labels, or presents a hypothesis as observed anatomy.",
        "fix": "Carry explicit source-fidelity and hypothesis-separation rules inside the manifest itself.",
        "check": "Manifest tests assert source pixels are preserved and hypothesis cannot be relabeled as observation.",
    },
    {
        "id": "11",
        "title": "Bring free segmentation back into MedForge",
        "module": "med_masks",
        "function": "load_mask_upload",
        "plain": "Import NIfTI anatomy masks created by TotalSegmentator or another segmentation tool without changing the original DICOM source.",
        "why": "Segmentation is derived data. Keeping it in a separate object lets us visualize and animate anatomy without pretending the mask is part of the original scan.",
        "input": ".nii, .nii.gz, or a ZIP of segmentation masks",
        "output": "One or more 3D boolean mask volumes with provenance",
        "failure": "A mask filename is treated as proven anatomy, an archive contains the wrong volume, or a mask is overlaid without spatial alignment checks.",
        "fix": "Keep imported masks labeled DERIVED / UNREVIEWED and require affine/orientation validation before source overlay.",
        "check": "Mask loader tests verify NIfTI/ZIP import and MedForge blocks overlay based only on matching dimensions.",
    },,
    {
        "id": "12",
        "title": "Hand the evidence-aware package to Forge",
        "module": "med_export",
        "function": "build_render_bundle",
        "plain": "Package the mechanism manifest and reviewed/derived masks so the animation engine receives geometry plus the evidence rules that govern it.",
        "why": "If we send only a pretty 3D model to the renderer, provenance can disappear. The bundle keeps the mask, affine, render rules, and evidence-boundary note together.",
        "input": "Render manifest, imported NIfTI masks, optional rendered source preview",
        "output": "Portable ZIP for the Forge rendering pipeline",
        "failure": "Raw DICOM or identifiers leak into a video handoff, or the renderer loses the distinction between source and reconstruction.",
        "fix": "Never include raw DICOM in the bundle, preserve mask affines, keep preview opt-in, and ship an evidence-boundary README with every package.",
        "check": "Bundle tests confirm manifest + NIfTI are present, affine is preserved, and no .dcm file is packaged.",
    },
]

PIPELINE = [
    "Source",
    "Privacy",
    "Series",
    "Volume",
    "MPR",
    "3D Preview",
    "Mask / Segmentation",
    "Image Understanding",
    "Mechanism",
    "Free Segmentation",
    "Render / Export",
]
