const {chromium}=require('playwright');
const fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const app of ['elias','evidence','grimforge','medforge']){
 await page.goto('http://127.0.0.1:8787/static/apps/'+app+'.html');await page.waitForSelector('#fcToggle');await page.screenshot({path:'test-output/'+app+'.png',fullPage:true});await page.click('#fcToggle');if(!await page.locator('#fcPanel').isVisible())throw Error('Copilot does not open');await page.click('#fcClose');
}
await page.goto('http://127.0.0.1:8787/static/apps/evidence.html');await page.click('button[data-panel="upload"]');
await page.locator('#uploadFile').setInputFiles([{name:'browser-evidence.txt',mimeType:'text/plain',buffer:Buffer.from('Browser fixture: sustained function requires recovery time.')}]);
await page.click('button[onclick="uploadAndBuild()"]');await page.waitForSelector('a:has-text("Download full PDF")',{timeout:30000});const href=await page.locator('a:has-text("Download full PDF")').getAttribute('href');const pdf=await page.request.get('http://127.0.0.1:8787'+href);if(!pdf.ok()||!(await pdf.body()).subarray(0,5).equals(Buffer.from('%PDF-')))throw Error('No PDF download');await page.screenshot({path:'test-output/evidence-built.png',fullPage:true});
await page.goto('http://127.0.0.1:8787/static/apps/elias.html');await page.waitForSelector('.welcome');await page.locator('#eliasAttachment').setInputFiles([{name:'elias-document.txt',mimeType:'text/plain',buffer:Buffer.from('Fixture independent Elias attachment')}]);await page.waitForFunction(()=>document.getElementById('attachmentStatus').textContent.includes('elias-document.txt'));await page.reload();await page.waitForSelector('#fcToggle');const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('forge.elias.threads.v1'))[0].documents);if(!stored?.length)throw Error('Attachment not retained');
// Browser UI routes with unavailable engine must show failure, not fake media success.
await page.goto('http://127.0.0.1:8787/static/apps/medforge.html');await page.fill('#fmPrompt','Fixture anatomy illustration');await page.click('#fmGenerate');await page.waitForFunction(()=>document.getElementById('fmResult').textContent.includes('No image workflow'),{timeout:15000});
await browser.close();fs.writeFileSync('test-output/ui-results.json',JSON.stringify({errors,passed:['Four app pages load and shared copilots open','Browser upload -> PDF package -> valid PDF download','Elias attachment survives reload','Missing media workflow shows explicit failure']},null,2));if(errors.length)throw Error(errors.join('\n'));console.log('Browser workflow checks passed');})();
