from __future__ import annotations

LESSONS = [
    {
        "id": "01",
        "title": "Creditless Mode is a policy, not a preference",
        "module": "servicebridge.local_runtime.runtime",
        "function": "RuntimePolicy",
        "plain": "Before an app calls a model or service, the runtime decides whether that destination is allowed.",
        "why": "A checkbox that says 'local' is meaningless if code can silently fall back to a paid endpoint.",
        "failure": "A local model is missing and the app automatically calls a cloud API.",
        "fix": "Creditless Mode blocks every non-loopback URL and disables cloud fallback.",
    },
    {
        "id": "02",
        "title": "Know the machine before choosing a model",
        "module": "servicebridge.local_runtime.runtime",
        "function": "detect_hardware",
        "plain": "Inspect CPU, RAM, NVIDIA GPU/VRAM when available, then assign a conservative local-compute tier.",
        "why": "The same workflow should choose a smaller model on a laptop and a larger model on a workstation instead of crashing.",
        "failure": "The app requests a model that cannot fit in RAM/VRAM.",
        "fix": "Use hardware tiers and explicit capability degradation.",
    },
    {
        "id": "03",
        "title": "Discover local engines",
        "module": "servicebridge.local_runtime.runtime",
        "function": "discover_services",
        "plain": "Check whether llama.cpp, Piper, FFmpeg, ComfyUI, or Ollama are installed/running.",
        "why": "Apps can adapt to what is actually available instead of assuming a paid provider exists.",
        "failure": "A button fails after the user waits because the required local service was never installed.",
        "fix": "Run the doctor first and show READY / INSTALLED / MISSING states.",
    },
    {
        "id": "04",
        "title": "Talk to a local brain",
        "module": "servicebridge.local_runtime.runtime",
        "function": "LocalOpenAICompatibleProvider",
        "plain": "Use the familiar OpenAI chat request shape against a localhost model server.",
        "why": "Elias and other apps can keep one provider interface while swapping cloud intelligence for local models.",
        "failure": "An endpoint points to the public internet while Creditless Mode is active.",
        "fix": "The provider re-checks the URL policy before every request.",
    },
    {
        "id": "05",
        "title": "Never regenerate the same asset",
        "module": "servicebridge.local_runtime.runtime",
        "function": "AssetCache",
        "plain": "Store files by cryptographic hash and keep provenance/parent relationships in SQLite.",
        "why": "Local AI can be slow. Reusing OCR, audio, masks, frames, and renders saves hours of compute.",
        "failure": "The same source gets processed repeatedly under different filenames.",
        "fix": "Address assets by content hash rather than filename.",
    },
    {
        "id": "06",
        "title": "Queue long local work",
        "module": "servicebridge.local_runtime.runtime",
        "function": "JobQueue",
        "plain": "Put segmentation, transcription, rendering, and generation into a small persistent SQLite queue.",
        "why": "Heavy local jobs should survive UI refreshes and be inspectable instead of freezing the app.",
        "failure": "Closing a browser tab loses the task state.",
        "fix": "Persist queued/running/completed/failed state outside the UI.",
    },
    {
        "id": "07",
        "title": "Transcribe without credits",
        "module": "servicebridge.local_runtime.workers",
        "function": "transcribe_file",
        "plain": "Use faster-whisper locally for speech-to-text.",
        "why": "WildTake, GrimForge, interviews, and evidence audio can all share one transcription engine.",
        "failure": "The model weights are not present and the first run unexpectedly needs the internet.",
        "fix": "Pre-download model weights for true offline mode and make model location explicit.",
    },
    {
        "id": "08",
        "title": "Narrate without credits",
        "module": "servicebridge.local_runtime.workers",
        "function": "run_piper",
        "plain": "Use Piper to synthesize narration on the local machine.",
        "why": "Video apps no longer need a per-character or per-minute voice API.",
        "failure": "No voice model is installed.",
        "fix": "Show the missing voice model in the runtime doctor and fall back to silent/captioned rendering, not cloud billing.",
    },
    {
        "id": "09",
        "title": "Generate locally when hardware permits",
        "module": "servicebridge.local_runtime.workers",
        "function": "ComfyUIClient",
        "plain": "Send a saved workflow to a local ComfyUI server.",
        "why": "Images and optional video generation become local capabilities rather than mandatory hosted services.",
        "failure": "The workflow requests a model that is not installed or exceeds available VRAM.",
        "fix": "Use hardware-aware workflow profiles and keep deterministic Forge rendering as the always-available fallback.",
    },
    {
        "id": "10",
        "title": "Always have a deterministic renderer",
        "module": "servicebridge.local_runtime.media",
        "function": "still_to_video_command",
        "plain": "Turn source images/frames into standards-compliant video with FFmpeg.",
        "why": "Even when no generative model fits the machine, Forge can still make a useful narrated video.",
        "failure": "The app equates 'AI video unavailable' with 'video unavailable.'",
        "fix": "Separate generative shot creation from deterministic video assembly.",
    },
    {
        "id": "11",
        "title": "Keep semantic memory local",
        "module": "servicebridge.local_runtime.memory",
        "function": "LocalVectorStore",
        "plain": "Store embeddings and metadata in SQLite, then score similarity on the local machine.",
        "why": "Elias should not require Pinecone, a hosted vector database, or a paid embedding provider to search evidence semantically.",
        "failure": "Evidence search stops working when a cloud vector service is unavailable.",
        "fix": "Use local embeddings plus SQLite; keep full-text search as a no-model fallback.",
    },
    {
        "id": "12",
        "title": "Read scanned documents locally",
        "module": "servicebridge.local_runtime.documents",
        "function": "paddle_ocr",
        "plain": "Run OCR on local images/PDF pages when embedded PDF text is missing.",
        "why": "Evidence ingestion should not upload private scans to an OCR API just to make them searchable.",
        "failure": "A scanned PDF has almost no extractable text and disappears from retrieval.",
        "fix": "Detect low-text pages, send only those pages through the local OCR worker, and cache the result.",
    },
    {
        "id": "13",
        "title": "Register models instead of downloading them silently",
        "module": "servicebridge.local_runtime.models",
        "function": "LocalModelCatalog",
        "plain": "Keep a catalog of model files already present on disk, including type, hardware needs, quality rank, and optional hash.",
        "why": "True offline mode needs to know exactly which model files are installed before the network is disconnected.",
        "failure": "An app discovers it needs weights only after a job starts and silently tries to download them.",
        "fix": "Provision models deliberately, register them, verify hashes, and select only compatible local files.",
    },
    {
        "id": "14",
        "title": "Fuse keyword and semantic evidence search locally",
        "module": "servicebridge.local_runtime.evidence",
        "function": "reciprocal_rank_fusion",
        "plain": "Combine SQLite full-text results with locally embedded semantic matches.",
        "why": "Exact terms are excellent for citations while semantic retrieval can recover differently worded evidence. Both can stay on-device.",
        "failure": "A hosted vector database outage removes semantic search, or semantic ranking hides exact record language.",
        "fix": "Keep FTS as the baseline, run embeddings locally, and fuse both ranked lists rather than replacing one with the other.",
    },
]

PIPELINE = [
    "Policy",
    "Hardware",
    "Service Discovery",
    "Local Brain",
    "Asset Vault",
    "Job Queue",
    "Speech",
    "Voice",
    "Image/Video AI",
    "FFmpeg Render",
    "Local Memory",
    "OCR",
    "Model Catalog",
    "Local Hybrid RAG",
]
