from __future__ import annotations

LESSONS = [
    {
        "id": "01",
        "title": "Creditless Mode is a policy, not a preference",
        "module": "servicebridge.local_runtime.runtime",
        "function": "RuntimePolicy",
        "plain": "Before an app calls a model or service, the runtime decides whether that destination is allowed.",
        "why": "A checkbox that says 'local' is meaningless if code can silently fall back to a paid endpoint.",
        "failure": "A local model is missing and the app automatically calls a cloud API.",
        "fix": "Creditless Mode blocks every non-loopback URL and disables cloud fallback.",
    },
    {
        "id": "02",
        "title": "Know the machine before choosing a model",
        "module": "servicebridge.local_runtime.runtime",
        "function": "detect_hardware",
        "plain": "Inspect CPU, RAM, NVIDIA GPU/VRAM when available, then assign a conservative local-compute tier.",
        "why": "The same workflow should choose a smaller model on a laptop and a larger model on a workstation instead of crashing.",
        "failure": "The app requests a model that cannot fit in RAM/VRAM.",
        "fix": "Use hardware tiers and explicit capability degradation.",
    },
    {
        "id": "03",
        "title": "Discover local engines",
        "module": "servicebridge.local_runtime.runtime",
        "function": "discover_services",
        "plain": "Check whether llama.cpp, Piper, FFmpeg, ComfyUI, or Ollama are installed/running.",
        "why": "Apps can adapt to what is actually available instead of assuming a paid provider exists.",
        "failure": "A button fails after the user waits because the required local service was never installed.",
        "fix": "Run the doctor first and show READY / INSTALLED / MISSING states.",
    },
    {
        "id": "04",
        "title": "Talk to a local brain",
        "module": "servicebridge.local_runtime.runtime",
        "function": "LocalOpenAICompatibleProvider",
        "plain": "Use the familiar OpenAI chat request shape against a localhost model server.",
        "why": "Elias and other apps can keep one provider interface while swapping cloud intelligence for local models.",
        "failure": "An endpoint points to the public internet while Creditless Mode is active.",
        "fix": "The provider re-checks the URL policy before every request.",
    },
    {
        "id": "05",
        "title": "Never regenerate the same asset",
        "module": "servicebridge.local_runtime.runtime",
        "function": "AssetCache",
        "plain": "Store files by cryptographic hash and keep provenance/parent relationships in SQLite.",
        "why": "Local AI can be slow. Reusing OCR, audio, masks, frames, and renders saves hours of compute.",
        "failure": "The same source gets processed repeatedly under different filenames.",
        "fix": "Address assets by content hash rather than filename.",
    },
    {
        "id": "06",
        "title": "Queue long local work",
        "module": "servicebridge.local_runtime.runtime",
        "function": "JobQueue",
        "plain": "Put segmentation, transcription, rendering, and generation into a small persistent SQLite queue.",
        "why": "Heavy local jobs should survive UI refreshes and be inspectable instead of freezing the app.",
        "failure": "Closing a browser tab loses the task state.",
        "fix": "Persist queued/running/completed/failed state outside the UI.",
    },
    {
        "id": "07",
        "title": "Transcribe without credits",
        "module": "servicebridge.local_runtime.workers",
        "function": "transcribe_file",
        "plain": "Use faster-whisper locally for speech-to-text.",
        "why": "WildTake, GrimForge, interviews, and evidence audio can all share one transcription engine.",
        "failure": "The model weights are not present and the first run unexpectedly needs the internet.",
        "fix": "Pre-download model weights for true offline mode and make model location explicit.",
    },
    {
        "id": "08",
        "title": "Narrate without credits",
        "module": "servicebridge.local_runtime.workers",
        "function": "run_piper",
        "plain": "Use Piper to synthesize narration on the local machine.",
        "why": "Video apps no longer need a per-character or per-minute voice API.",
        "failure": "No voice model is installed.",
        "fix": "Show the missing voice model in the runtime doctor and fall back to silent/captioned rendering, not cloud billing.",
    },
    {
        "id": "09",
        "title": "Generate locally when hardware permits",
        "module": "servicebridge.local_runtime.workers",
        "function": "ComfyUIClient",
        "plain": "Send a saved workflow to a local ComfyUI server.",
        "why": "Images and optional video generation become local capabilities rather than mandatory hosted services.",
        "failure": "The workflow requests a model that is not installed or exceeds available VRAM.",
        "fix": "Use hardware-aware workflow profiles and keep deterministic Forge rendering as the always-available fallback.",
    },
    {
        "id": "10",
        "title": "Always have a deterministic renderer",
        "module": "servicebridge.local_runtime.media",
        "function": "still_to_video_command",
        "plain": "Turn source images/frames into standards-compliant video with FFmpeg.",
        "why": "Even when no generative model fits the machine, Forge can still make a useful narrated video.",
        "failure": "The app equates 'AI video unavailable' with 'video unavailable.'",
        "fix": "Separate generative shot creation from deterministic video assembly.",
    },
    {
        "id": "11",
        "title": "Keep semantic memory local",
        "module": "servicebridge.local_runtime.memory",
        "function": "LocalVectorStore",
        "plain": "Store embeddings and metadata in SQLite, then score similarity on the local machine.",
        "why": "Elias should not require Pinecone, a hosted vector database, or a paid embedding provider to search evidence semantically.",
        "failure": "Evidence search stops working when a cloud vector service is unavailable.",
        "fix": "Use local embeddings plus SQLite; keep full-text search as a no-model fallback.",
    },
    {
        "id": "12",
        "title": "Read scanned documents locally",
        "module": "servicebridge.local_runtime.documents",
        "function": "paddle_ocr",
        "plain": "Run OCR on local images/PDF pages when embedded PDF text is missing.",
        "why": "Evidence ingestion should not upload private scans to an OCR API just to make them searchable.",
        "failure": "A scanned PDF has almost no extractable text and disappears from retrieval.",
        "fix": "Detect low-text pages, send only those pages through the local OCR worker, and cache the result.",
    },
    {
        "id": "13",
        "title": "Register models instead of downloading them silently",
        "module": "servicebridge.local_runtime.models",
        "function": "LocalModelCatalog",
        "plain": "Keep a catalog of model files already present on disk, including type, hardware needs, quality rank, and optional hash.",
        "why": "True offline mode needs to know exactly which model files are installed before the network is disconnected.",
        "failure": "An app discovers it needs weights only after a job starts and silently tries to download them.",
        "fix": "Provision models deliberately, register them, verify hashes, and select only compatible local files.",
    },
    {
        "id": "14",
        "title": "Fuse keyword and semantic evidence search locally",
        "module": "servicebridge.local_runtime.evidence",
        "function": "reciprocal_rank_fusion",
        "plain": "Combine SQLite full-text results with locally embedded semantic matches.",
        "why": "Exact terms are excellent for citations while semantic retrieval can recover differently worded evidence. Both can stay on-device.",
        "failure": "A hosted vector database outage removes semantic search, or semantic ranking hides exact record language.",
        "fix": "Keep FTS as the baseline, run embeddings locally, and fuse both ranked lists rather than replacing one with the other.",
    },
    {
        "id": "15",
        "title": "Generate still images without a separate app",
        "module": "servicebridge.local_runtime.image",
        "function": "generate_image_local",
        "plain": "Load an already-downloaded Diffusers model directly in Python and generate a still image.",
        "why": "ComfyUI is useful, but our core image-generation path should not require a separate GUI/server.",
        "failure": "The requested model weights are absent and a library tries to fetch them from the internet.",
        "fix": "Use local_files_only=True and fail clearly when the local model directory is incomplete.",
    },
    {
        "id": "16",
        "title": "Register reusable local generation workflows",
        "module": "servicebridge.local_runtime.workflows",
        "function": "LocalWorkflowCatalog",
        "plain": "Keep saved image/video workflow JSON files in a verified local catalog.",
        "why": "Complex local generation graphs should be reusable assets, not one-off manual setup.",
        "failure": "A workflow disappears, changes silently, or points at unavailable models.",
        "fix": "Register local JSON files, hash/verify them, and substitute only explicit variables.",
    },
    {
        "id": "17",
        "title": "Create captions deterministically",
        "module": "servicebridge.local_runtime.captions",
        "function": "scene_narration_to_cues",
        "plain": "Turn known scene narration and durations into SRT cues without an AI captioning service.",
        "why": "When the script is already known, basic captions should cost nothing and require no inference.",
        "failure": "A project waits for a transcription API even though the narration text is already in the scene plan.",
        "fix": "Build scene-level captions directly; use local Whisper only when word-level timing is actually needed.",
    },
    {
        "id": "18",
        "title": "Finish the video locally",
        "module": "servicebridge.local_runtime.render",
        "function": "render_plan",
        "plain": "Render scene images, narration or silence, captions, and final assembly into an MP4 with FFmpeg.",
        "why": "Generative video should improve shots, not determine whether Forge can export a movie at all.",
        "failure": "No video model or GPU means the project cannot export anything.",
        "fix": "Use source-locked/generated stills plus local audio and deterministic motion/assembly as the always-available render path.",
    },
    {
        "id": "19",
        "title": "Generate video directly from local model files",
        "module": "servicebridge.local_runtime.video",
        "function": "generate_video_local",
        "plain": "Load an already-downloaded Diffusers-compatible text-to-video model directly in Python and export its frames to MP4.",
        "why": "ComfyUI should be optional. When the machine can run a compatible model, Forge can call the model itself without a hosted service or a separate generation app.",
        "failure": "A generic profile passes unsupported parameters, a huge model exceeds VRAM, or missing weights trigger an internet download.",
        "fix": "Inspect the loaded pipeline signature, pass only supported parameters, use hardware/model profiles, and require local_files_only=True.",
    },
    {
        "id": "20",
        "title": "Use a higher-quality local voice without cloud TTS",
        "module": "servicebridge.local_runtime.tts",
        "function": "generate_kokoro_local",
        "plain": "Run Kokoro locally for narration while forcing Hugging Face/Transformers offline mode.",
        "why": "Piper gives us a lightweight CPU baseline, while Kokoro gives the apps a second local voice-quality tier without per-character credits.",
        "failure": "Kokoro lazily requests a missing model or voice file from the internet.",
        "fix": "Force model-hub offline flags before pipeline creation and fail if the required model/voice is not already cached.",
    },,
    {
        "id": "21",
        "title": "Auto-fallback between local voice engines",
        "module": "servicebridge.local_runtime.speech",
        "function": "generate_speech_local_auto",
        "plain": "Try offline Kokoro first, fall back to an explicitly configured local Piper voice, and stop there.",
        "why": "A missing premium-quality voice should not turn into a cloud bill or block the entire video.",
        "failure": "Kokoro is missing and the app silently calls a hosted TTS provider.",
        "fix": "Keep the fallback chain local-only; if both local engines fail, the media apps render captions plus silence.",
    },
    {
        "id": "22",
        "title": "Understand images with a localhost VLM",
        "module": "servicebridge.local_runtime.vision",
        "function": "LocalVisionClient",
        "plain": "Send text plus an image data URI to an OpenAI-compatible vision model running on loopback.",
        "why": "MedForge and future image-aware tools should not require hosted multimodal inference.",
        "failure": "A local vision configuration is missing and the app falls back to an external endpoint.",
        "fix": "Run the same Creditless URL policy before client creation and before every request.",
    },
    {
        "id": "23",
        "title": "Preserve the runtime for offline reinstall",
        "module": "servicebridge.local_runtime.offline",
        "function": "build_offline_pack",
        "plain": "Create a verified ZIP of safe repo code, optional wheel files, registered workflows, and only explicitly requested registered model files.",
        "why": "Local independence is fragile if reinstalling the machine means rebuilding the stack from memory or redownloading everything.",
        "failure": "A backup pack accidentally captures evidence databases, .env secrets, caches, or unrelated private files.",
        "fix": "Use a strict whitelist for repo content, deny private_data/.env/caches, and require an explicit flag before model binaries are included.",
    },
]

PIPELINE = [
    "Policy",
    "Hardware",
    "Service Discovery",
    "Local Brain",
    "Asset Vault",
    "Job Queue",
    "Speech",
    "Voice",
    "Image/Video AI",
    "FFmpeg Render",
    "Local Memory",
    "OCR",
    "Model Catalog",
    "Local Hybrid RAG",
    "Direct Image Gen",
    "Workflow Catalog",
    "Captions",
    "Direct Video Gen",
    "Local Kokoro Voice",
    "Local Voice Fallback",
    "Local Vision",
    "Offline Pack",
    "Final Local Render",
]
